### PR TITLE
I am American and my first name is Talon

### PR DESCRIPTION
**Pull request by talon**
does Talon sound American I think it does. Ship it.

### CODE REVIEW

**Comment by dannyfritz** [comment]
Sounds as American as a friggin' Bald Eagle's talons. MURICA

**Comment by chrisinajar** [comment]
Are you implying that `Muhamed`, `Ahmed`, `Carlos`, `Adnan`, and `Farid` are not american enough sounding to be including in npm infamy? You, sir, need another credit card.

image

**Comment by wesbos** [comment]
🇺🇸🇺🇸🇺🇸🇺🇸

**Comment by talon** [comment]
@chrisinajar Was not my intention to remove names. Just add my own. Fixed.

**Pull request merged**
