### PR TITLE
Update first.json to add 대영

### PR DESCRIPTION
**Pull request by sreynen**
My American son's first name.

### CODE REVIEW

**Comment by chrisinajar** [comment]
This commit conflicts. Also, does the name have a US keyboard layout alternative? It's not "american names", it's "american _sounding_ names", and as an uneducated american I cannot sound that out.

Tell me, sweet prince, the sounds of freedom.

**Comment by sreynen** [comment]
I can update from master to fix the conflict, but the definition of "American sounding" seems like the larger issue here. I expect most uneducated American's don't know how "Jesus" sounds (in the context of an American name). Maybe that should be removed? And if uneducated American pronunciation is the criteria for inclusion, that should probably be explicitly stated somewhere, maybe even in the name.

**Comment by chrisinajar** [comment]
You're right that an accurate pronunciation is not achievable, but I think the goal should be an attemptable pronunciation. It's just easier if we use the English alphabet (note, not american, english, as that is the language)

To me, "american" is literally any name written in the English alphabet, regardless of difficulty of pronunciation.

**Comment by sreynen** [comment]
Fair enough. Thanks for clearing up the guidelines.

**Comment by chrisinajar** [comment]
@sreynen Also, let be known the this was created as a joke as part of an interview challenge that I didn't finish. It's designed specifically to be a bit tongue-in-cheek  and offensive, so keep that in mind.

Hilariously, a few people are actually using it for generating fixtures.

**Pull request closed without merging**
